version: '3'

services:
  api:
    image: localhost:5498/nx-go-api:0.0.1
    env_file:
      - .env
    ports:
      - "8002:8001"
    depends_on:
      - db

  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: r00t
      MYSQL_DATABASE: api
      MYSQL_USER: us3r
      MYSQL_PASSWORD: p455
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3307:3306"

volumes:
  db_data:
